name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    uses: pkgjs/action/.github/workflows/node-test.yaml@v0
    with:
      upgrade-policy: lts
    - run: npm ci
    - name: Checking JS types
      run: npm run check
      continue-on-error: true
    - run: npm test
